---
- name: Automatic Remediation from Alert Manager
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen for alerts from Alert Manager
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8000
  rules:
    - name: Prometheus Node Exporter Down
      condition: event.payload.alerts[0].labels.alertname == "ExporterDown" and event.payload.alerts[0].status == "firing" and event.payload.alerts[0].labels.job != "tower metrics"
      action:
        run_workflow_template:
          name: "Automated Response Node Exporter Down EDA"
          organization: "Security"
          job_args:
            extra_vars:
              vm_name: "{{ event.alert.labels.job }}"

    - name: SELinux Disabled
      condition: event.payload.alerts[0].labels.alertname == "SELinuxDisabled" and event.payload.alerts[0].status == "firing"
      action:
        run_job_template:
          name: "EDA Automated Response SELinux Disabled"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              vm_name: "{{ event.alert.labels.job }}"
