---
- name: Listen for events on a webhook from Mattermost
  hosts: all
  sources:
    - name: Listen for alerts from Mattermost
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Webhook Event from Mattermost for RHEL Patching
      condition: event.payload.channel_name  == "town-square" and event.payload.trigger_word == "Patch_RHEL"
      action:
        run_job_template:
          name: "Patching RHEL"
          organization: "Infrastructure"

    - name: Webhook Event from Mattermost for Windows Patching
      condition: event.payload.channel_name  == "town-square" and event.payload.trigger_word == "Patch_Windows"
      action:
        run_job_template:
          name: "Patching Windows"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              categories:
                - '*'
              reboot_server: 'yes'
