---
- name: Listen for events on a webhook from Datadog
  hosts: all
  sources:
    - name: Listen for alerts from Datadog
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4999

  rules:
    - name: Web Application Down Detected
      condition: event.payload.event_title == "[Triggered] Web Server is Down"
      action:
        run_workflow_template:
          name: "Ansible AI Response"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.hostname }}"
              service_issue: "httpd"
