---
- name: Listen for events on a webhook from Datadog
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8001
        certfile: /certs/shadowman_cert.cer
        keyfile: /certs/shadowman_private.key
        token: "{{ eda_auth_token }}"

  rules:
    - name: See all datadog alerts
      condition: event.meta is defined
      action:
        debug:
