---
- name: Listen for events on a webhook from Datadog
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 4999
        certfile: /certs/shadowman_cert.cer
        keyfile: /certs/shadowman_private.key
        token: "{{ eda_auth_token }}"

  rules:
    - name: High CPU Usage Detected
      condition: event.payload.event_title == "[Triggered] CPU Load is high"
      action:
        run_workflow_template:
          name: "Automated Response High CPU EDA"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.hostname }}"

    - name: Web Application Down Detected
      condition: event.payload.event_title == "[Triggered] Web Server is Down"
      action:
        run_workflow_template:
          name: "Automated Response Web Server EDA"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.hostname }}"

    - name: See all other datadog alerts
      condition: event.meta is defined and event.payload.event_title != "[Triggered] CPU Load is high and event.payload.event_title != "[Triggered] Web Server is Down"
      action:
        debug:
