---
- name: Listen for events on a webhook from Inventory
  hosts: all
  sources:
    - name: Listen for alerts from Inventory
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4998

  rules:
    - name: Call Inventory Job Template
      condition: event.meta is defined
      action:
        run_job_template:
          name: "A Simple Test"
          organization: "Infrastructure"
          job_args:
            inventory: "Localhost Inventory"
