---
- name: Events from Windows Logs

  hosts: all
  sources:
    - name: Kafka listener for Windows logs topic
      ansible.eda.kafka:
        host: kafka.shadowman.dev
        port: 9092
        topic: windowslogs
        group_id: ansible-eda-winlogbeat

  rules:
  # https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/security-auditing-overview
  # https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-user-account-management
    - name: A Windows / AD User Account was enabled
      condition: event.body.winlog.event_id == "4722"
      action:
        run_job_template:
          name: "Remove Local Windows User"
          organization: Infrastructure
          job_args:
            extra_vars:
              vm_name: "{{ event.body.winlog.computer_name }}"
              usertodelete: "{{ event.body.winlog.event_data.TargetUserName }}"
  # https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5025
  # https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4950
  # https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/monitor-the-resource-attributes-on-files-and-folders

    - name: A Firewall Event was detected
      condition: event.body.message is search ("The Windows Firewall service")
      action:
        run_job_template:
          name: "Firewall Event"
          organization: Infrastructure
          job_args:
            extra_vars:
              vm_name: "{{ event.body.winlog.computer_name }}"
              message: "{{ event.body.message }}"
              event_id: "{{ event.body.winlog.event_id | string }}"
