---
- name: Events from Auditbeat

  hosts: all
  sources:
    - name: Kafka listener for Auditbeat logs topic
      ansible.eda.kafka:
        host: kafka.shadowman.dev
        port: 9092
        topic: auditbeat

  rules:
    - name: The web server was modifie on Windows
      condition:
        all:
          - event.body.file.path is match("C:\\inetpub\\wwwroot\\", ignorecase=true)
          - event.body.error is not defined
      action:
        run_job_template:
          name: "EDA Web Application"
          organization: Application Development
          job_args:
            extra_vars:
              vm_name: "{{ event.body.host.hostname }}.ad.shadowman.dev"
