---
- name: Events from Auditbeat

  hosts: all
  sources:
    - name: Kafka listener for Auditbeat logs topic
      ansible.eda.kafka:
        host: kafka.shadowman.dev
        port: 9092
        topic: auditbeat
        group_id: ansible-eda-audit

  rules:
    - name: The web server was modified on Windows
      condition: event.body.file.path is match("C:\\inetpub\\wwwroot\\", ignorecase=true)
      action:
        run_job_template:
          name: "EDA Web Application"
          organization: Application Development
          job_args:
            extra_vars:
              vm_name: "{{ event.body.host.hostname }}.ad.shadowman.dev"

    - name: The web server was modified on RHEL
      condition: event.body.file.path is match("/var/www/html/", ignorecase=true)
      action:
        run_job_template:
          name: "EDA Web Application"
          organization: Application Development
          set_facts:
          job_args:
            extra_vars:
              vm_name: "{{ event.body.host.hostname }}"
