---
- name: Events from Windows Logs

  hosts: all
  sources:
    - name: Kafka listener for Windows logs topic
      ansible.eda.kafka:
        host: kafka.shadowman.dev
        port: 9092
        topic: windowslogs

  rules:
  # https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-user-account-management
    - name: A User Account was created
      condition: event.body.winlog.event_id == "4722"
      action:
        debug:

    - name: Firewall disabled
      condition: event.body.winlog.event_id == "4950"
      action:
        debug:
