---
- name: Events from gNMI

  hosts: all
  sources:
    - name: Kafka listener for network topic
      ansible.eda.kafka:
        host: kafka.shadowman.dev
        port: 9092
        topic: network
        group_id: ansible-eda-gnmi

  rules:
    - name: A Down Interface has been detected
      condition: event.body.fields.admin_status == "DOWN"
      action:
        run_job_template:
          name: "Network Interface Remediation"
          organization: Networking
          job_args:
            extra_vars:
              downinterface: "{{ event.body.tags.name }}"
              device: "{{ event.body.tags.source }}"
