---
- name: Listen for events on a webhook from LM
  hosts: all
  sources:
    - name: Listen for alerts from LM
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4998

  rules:
    - name: High CPU Usage Detected
      condition: event.payload.datasource == "CPU / Memory" and event.payload.datapoint == "1MinLoadPerCoreAvg" and event.payload.status == "active"
      action:
        run_workflow_template:
          name: "Automated Response High CPU EDA"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.host }}"

    - name: Web Application Down Detected
      condition: event.payload.datasource == "HTTPS-443" and event.payload.datapoint == "CantConnect" and event.payload.status == "active"
      action:
        run_workflow_template:
          name: "Automated Response Web Server EDA"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.host }}"

    - name: See all other LM alerts
      condition: event.meta is defined
      action:
        debug:
