---
- name: Listen for events on a webhook from LM
  hosts: all
  sources:
    - name: Listen for alerts from LM
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4998

  rules:
    - name: Output LM Information
      condition: event.meta is defined
      action:
        debug:
