---
- name: Rulebook Bracket test
  hosts: all
  sources:
    - name: Listen for alerts from Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4994
        certfile: /certs/shadowman_cert.cer
        keyfile: /certs/shadowman_private.key
  rules:
    - name: Prometheus Node Exporter Down
      condition: event.alert.labels.alertname[0].name == "ExporterDown"
      action:
        run_workflow_template:
          name: "Automated Response Node Exporter Down EDA"
          organization: "Security"
          job_args:
            extra_vars:
              vm_name: "{{ event.alert.labels.job }}"
