---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 4994

  rules:
    - name: Execute the SecOps EDA test job template
      condition:
        all:
          - event.payload.issue.fields.project.name == "MS - Global SecOps"
          - event.payload.webhookEvent == "jira:issue_created"
          - event.payload.issue.fields.issuetype.name == "Internal Security Scan Request"
          - event.payload.issue.fields.customfield_11612[0].value == "Tenable SecurityCenter"
          - event.payload.issue.fields.customfield_15123 != "None"
      actions:
        - debug:
