---
- name: Generic new poll for new records in ServiceNow
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Watch for any updated table
      servicenow.itsm.records:
        table: "{{ servicenow_table }}"
        interval: "{{ servicenow_interval }}"

  rules:

    - name: New record created and debug
      condition: event.sys_id is defined
      action:
        debug:
