---
- name: Listen for events on a webhook from ServiceNow
  hosts: all
  sources:
    - name: Listen for alerts from ServiceNow
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4998

  rules:
    - name: Output ServiceNow Information
      condition: event.meta is defined
      action:
        debug:
