---
- name: Respond to ServiceNow catalog request items
  hosts: all
  sources:
    - name: Listen for alerts from ServiceNow EDA Notification Service
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:

    - name: Enrich new REQ received from Service Catalog
      condition: event.payload.sys_class_name == "sc_request"
      action:
        run_job_template:
          name: "EDA Enrich ServiceNow REQ"
          organization: Infrastructure
          post_events: true
          job_args:
            extra_vars:
              req_sys_id: "{{ event.payload.sys_id }}"
              req_number: "{{ event.payload.number }}"

    - name: New Multi Provision VM Request
      condition: event.enriched_event.ritm_details is selectattr('cat_item.display_value', '==', "AAP EDA Multi Provision w/ Citrix")
      action:
        debug:
