---
- name: Listen for events on a webhook from Splunk
  hosts: all
  sources:
    - name: Listen for alerts from Splunk
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5010

  rules:
    - name: Webhook Event from Splunk for RHEL Local User Created
      condition: event.payload.results.process  == "useradd"
      action:
        run_job_template:
          name: "Remove Local User"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.results.host }}"
              user_name: "{{ event.payload.results.name }}"
              logs: "{{ event.payload.results._raw }}"

    - name: A Down Interface has been detected
      condition: event.payload.results.eventtype == "cisco_ios cisco_ios-ios cisco_ios-port_down"
      action:
        run_job_template:
          name: "Network Interface Remediation"
          organization: Networking
          job_args:
            extra_vars:
              downinterface: "{{ event.payload.results.src_interface }}"
              device: "{{ event.payload.results.dvc }}"
