---
- name: Listen for events on a webhook from VMware
  hosts: all
  sources:
    - name: Listen for alerts from VMWare
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003
        token: "{{ eda_auth_token }}"

  rules:
    - name: Alert for ESX Host Memory
      condition: event.payload.vmware_alert.alarm == "alarm.HostMemoryUsageAlarm"
      action:
        run_job_template:
          name: "Migrate VMWare VM For ESX Memory"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              overloadedesx: "{{ event.payload.vmware_alert.target }}"

    - name: Alert for ESX Host CPU
      condition: event.payload.vmware_alert.alarm == "alarm.HostCPUUsageAlarm"
      action:
        run_job_template:
          name: "Migrate VMWare VM For ESX CPU"
          organization: "Infrastructure"
          job_args:
            extra_vars:
              overloadedesx: "{{ event.payload.vmware_alert.target }}"
