---
- name: Listen for events on a webhook from VMWare
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Alert for ESX Host Memory
      condition: event.payload.vmware_alert.alarm == "alarm.HostMemoryUsageAlarm"
      action:
        debug:

    - name: Alert for ESX Host CPU
      condition: event.payload.vmware_alert.alarm == "alarm.HostCPUUsageAlarm"
      action:
        debug:
